# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - 'dependencies'
      - 'ignore-for-release'

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    registries: "*"
    open-pull-requests-limit: 20
    labels:
      - 'dependencies'
    groups:
      kotlin-ksp-compose:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.jvm"
          - "com.google.devtools.ksp"
          - "androidx.compose.compiler:compiler"

  - package-ecosystem: swift
    directory: "/app/ios/Modules"
    schedule:
      interval: daily
    labels:
      - 'dependencies'

registries:
  maven-google:
    type: "maven-repository"
    url: "https://maven.google.com"
    replaces-base: true
