# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: swift
    directory: "/app/ios/Modules"
    schedule:
      interval: daily
