# noinspection YAMLSchemaValidation
version: 1

labels:
  # Type labels
  - label: "@type/build"
    title: '^build(?:\(.+\))?\!?:'
    files:
      - "**/*.gradle.kts$"
      - "build-logic/**/*"

  - label: "@type/ci"
    title: '^ci(?:\(.+\))?\!?:'
    files:
      - '\.github/.+'
      - "scripts/.+"
      - "tools/.+"

  - label: "@type/docs"
    title: '^docs:(?:\(.+\))?\!?:'
    files:
      - "docs/.+"
      - "**/README.md$"

  - label: "@type/feature"
    title: '^feat:(?:\(.+\))?\!?:'

  - label: "@type/fix"
    title: '^fix:(?:\(.+\))?\!?:'

  - label: "@type/improve"
    title: '^(style|refactor|perf)(?:\(.+\))?\!?:'

  # App Module labels
  - label: "@app/android"
    files:
      - "app/android/.+"

  - label: "@app/backend"
    files:
      - "app/backend/.+"

  - label: "@app/frontend"
    files:
      - "app/frontend/.+"
      - "app/web/.+"

  - label: "@app/ios"
    files:
      - "app/ios/.+"
      - "app/ios-combined/.+"

  - label: "@app/shared"
    files:
      - "app/shared/.+"

  # Core Module labels
  - label: "@core/analytics"
    files:
      - "core/analytics/.+"

  - label: "@core/common"
    files:
      - "core/common/.+"

  - label: "@core/data"
    files:
      - "core/data/.+"

  - label: "@core/database"
    files:
      - "core/database/.+"

  - label: "@core/datastore"
    files:
      - "core/datastore/.+"

  - label: "@core/designsystem"
    files:
      - "core/designsystem/.+"

  - label: "@core/domain"
    files:
      - "core/domain/.+"

  - label: "@core/model"
    files:
      - "core/model/.+"

  - label: "@core/network"
    files:
      - "core/network/.+"

  - label: "@core/testing"
    files:
      - "core/testing/.+"

  - label: "@core/ui"
    files:
      - "core/ui/.+"

  # Feature Module labels
  - label: "@feature/auth"
    files:
      - "feature/auth/.+"

  - label: "@feature/schedule"
    files:
      - "feature/schedule/.+"

  - label: "@feature/settings"
    files:
      - "feature/settings/.+"

  - label: "@feature/top"
    files:
      - "feature/top/.+"
