name: "Backend CI"

on:
  pull_request_target:

# Cancel any current or previous job from the same PR
concurrency:
  group: backend-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Unit Tests
        run: ./gradlew :app:backend:check

      - name: Build
        run: ./gradlew :app:backend:buildFatJar
