name: "iOS CI"

on:
  pull_request_target:

# Cancel any current or previous job from the same PR
concurrency:
  group: ios-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build iOS framework
        run: ./gradlew :app:ios-combined:assembleNitoKmpReleaseXCFramework

      - name: Build iOS app
        run: xcodebuild -project ios/App/Nito/Nito.xcodeproj -configuration Debug -scheme Dev -sdk iphoneos -destination name='iPhone 8' build

      - name: Run iOS unit tests
        run: xcodebuild test -project ios/App/Nito/Nito.xcodeproj -configuration Debug -scheme Dev -sdk iphoneos -destination name='iPhone 8' build -test-timeouts-enabled YES
